language: node_js
node_js: 
  - "8"
cache:
  directories:
    - "node_modules"
install: 
  - npm install
script: 
  - git config --global user.email "chenwangji@hebao.im"
  - git config --global user.name "chenwangji"
  - npm run deploy